# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'trampfox-prometheus'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Here it's Prometheus itself.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 10 seconds.
    scrape_interval: 10s

    static_configs:
      - targets: ['localhost:9090']


# - job_name: 'cadvisor'
    # Override the global default and scrape targets from this job every 5 seconds.
    #scrape_interval: 5s

    #dns_sd_configs:
    #- names:
    #  - 'tasks.cadvisor'
    #  type: 'A'
    #  port: 8080

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    
    static_configs:
      - targets: ['localhost:9100']
