{
 "title": "Openweather - Turin",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(openweather_temperature{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"} - 32) * 5/9"
    }
   ]
  },
  {
   "title": "Feelslike",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "(openweather_feelslike{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"} - 32) * 5/9"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "openweather_humidity{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"}",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    { "expr": "openweather_pressure" }
   ]
  },
  {
   "title": "Wind speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "openweather_windspeed{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"} / 10"
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "openweather_sunrise{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"} * 1000"
    }
   ]
  },
  {
   "title": "Sunset",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "openweather_sunset{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"} * 1000"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(openweather_temperature{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"} - 32) * 5/9",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "openweather_humidity{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"}",
     "legendFormat": "{{ location }}"
    }
   ]
  },
  {
   "title": "Rain last 1h (mm)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "expr": "openweather_rain1h{instance=\"openweather-exporter:9091\",job=\"openweather-exporter\",location=\"Turin, IT\"}",
     "legendFormat": "{{ location }}"
    }
   ]
  }
 ]
}